before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=1
    targets:
      - linux_amd64
    ldflags:
      - -s -w -extldflags=-static -X mtui/app.Version={{.Version}}
changelog:
  sort: asc
